import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Badge, Btn, Card, CardHeader, PageHeader } from "@/components/admin/ui";
import { getAdminSession } from "@/lib/admin-auth";

export const Route = createFileRoute("/admin/payments")({ component: PaymentsPage });
function PaymentsPage() {
  const [payments, setPayments] = useState<any[]>([]); const [selected, setSelected] = useState<any>(null); const [reason, setReason] = useState("");
  const load = () => fetch("/api/payments", { credentials: "same-origin" }).then(r => r.json()).then(d => { setPayments(d.payments || []); setSelected((d.payments || [])[0] || null); }).catch(() => undefined);
  useEffect(() => { if (getAdminSession()?.role === "Operations Staff") return; load(); }, []);
  async function review(action: string) { if (!selected) return; const proof = selected.payment_proofs?.find((p: any) => p.is_current); const r = await fetch("/api/payments", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ paymentId: selected.id, action, reason, proofVersion: proof?.version, submittedAmount: selected.submitted_amount, transactionReference: selected.transaction_reference }) }); const body = await r.json().catch(() => ({})); if (!r.ok) return alert(body.message || "Unable to save review"); load(); setReason(""); }
  if (getAdminSession()?.role === "Operations Staff") return <div className="p-8">Payment information is restricted.</div>;
  return <div><PageHeader title="Payments" subtitle="Owner/Admin manual verification queue" /><Card><CardHeader title="Payment queue" hint="Payment status is separate from booking status" /><div className="divide-y divide-border">{payments.map(p => <button key={p.id} onClick={() => setSelected(p)} className="flex w-full items-center justify-between p-4 text-left hover:bg-secondary/40"><span>{p.booking_id.slice(0,8)} · {p.payment_method_label || "Method"}<small className="ml-2 text-muted-foreground">{p.transaction_reference}</small></span><Badge>{p.status}</Badge></button>)}</div></Card>{selected && <Card><CardHeader title="Review payment" hint={selected.booking_id} /><div className="space-y-3 p-5 text-sm"><p>Customer: {selected.customer_id}</p><p>Method: {selected.payment_method_label}</p><p>Amount: PHP {selected.submitted_amount}</p><p>Reference: {selected.transaction_reference}</p>{selected.payment_proofs?.find((p: any) => p.is_current) && <button className="text-primary underline" onClick={async () => { const proof = selected.payment_proofs.find((p: any) => p.is_current); const r = await fetch(`/api/payments?proofId=${proof.id}`, { credentials: "same-origin" }); const b = await r.json(); if (r.ok) window.open(b.url, "_blank"); }}>Open current proof securely</button>}<textarea className="input-control" placeholder="Customer-facing reason (required for resubmission)" value={reason} onChange={e => setReason(e.target.value)} /><div className="flex gap-2"><Btn onClick={() => review("verify")}>Verify</Btn><Btn variant="danger" onClick={() => review("resubmit")}>Request Resubmission</Btn><Btn variant="ghost" onClick={() => review("pending")}>Leave Pending</Btn></div></div></Card>}</div>;
}
