import { createFileRoute } from "@tanstack/react-router";
import { requirePrincipal } from "@/lib/auth.server";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { addWeeks, calculateWma, extractWeeklyDemand, isoDay, loadCanonicalBookings, loadDemandCoverage, manilaWeekStart, mapeFromDatabaseRows } from "@/lib/forecasting.server";

export const Route = createFileRoute("/api/forecasts")({ server: { handlers: { GET: read, POST: mutate } } });
const denied = (s: number, m: string) => Response.json({ message: m }, { status: s });
async function read() { try { const p = await requirePrincipal(); if (p.role === "Customer/Renter") return denied(403, "Forecast access is restricted."); const c = getSupabaseServerClient() as any; const [runs, records] = await Promise.all([c.from("forecast_runs").select("*").order("generated_at", { ascending: false }), c.from("forecasts").select("*, inputs:forecast_inputs(*)").order("target_week_start")]); if (runs.error || records.error) return denied(503, "Unable to load forecasts."); return Response.json({ runs: runs.data ?? [], forecasts: records.data ?? [], mape: mapeFromDatabaseRows(records.data ?? []) }); } catch (e) { return denied(e instanceof Error && e.message === "forbidden" ? 403 : 401, e instanceof Error && e.message === "forbidden" ? "Forbidden." : "Authentication required."); } }
async function mutate({ request }: { request: Request }) { try { const p = await requirePrincipal(); if (p.role !== "Owner/Admin") return denied(403, "Owner/Admin access is required."); const body = await request.json().catch(() => ({})); const c = getSupabaseServerClient() as any; const action = body?.action === "finalize" ? "finalize" : "generate"; const rows = await loadCanonicalBookings(); const coverage = await loadDemandCoverage(); const actualMap = extractWeeklyDemand(rows, coverage); if (action === "finalize") { const current = isoDay(manilaWeekStart(new Date())); const existing = await c.from("forecasts").select("*").lt("target_week_start", current).is("actual_demand", null); for (const r of existing.data ?? []) { const actual = (actualMap.get(`${r.branch_id}:${r.vehicle_category_id}`) ?? []).find((x: any) => x.weekStart === r.target_week_start); if (actual) { const u = await c.from("forecasts").update({ actual_demand: actual.demand, ape: actual.demand > 0 ? Math.abs((actual.demand - Number(r.forecasted_demand)) / actual.demand) * 100 : null }).eq("id", r.id); if (u.error) throw u.error; } } return Response.json({ finalized: existing.data?.length ?? 0 }); }
 const key = typeof body?.idempotencyKey === "string" ? body.idempotencyKey.trim() : ""; if (!key) return denied(400, "idempotencyKey is required."); const existing = await c.from("forecast_runs").select("*").eq("idempotency_key", key).maybeSingle(); if (existing.data) return Response.json(existing.data); const branches = await c.from("branches").select("id").eq("is_active", true); const cats = await c.from("vehicle_categories").select("id").eq("is_active", true); const anchor = addWeeks(manilaWeekStart(new Date()), -1); const records: any[] = []; const inputs: any[] = []; let n = 0; for (const b of branches.data ?? []) for (const cat of cats.data ?? []) { const wma = calculateWma(actualMap.get(`${b.id}:${cat.id}`) ?? []); if (!wma) continue; for (let i = 0; i < 3; i++) { const clientRecordId = `r${n++}`; const target = addWeeks(anchor, i + 1); records.push({ client_record_id: clientRecordId, branch_id: b.id, vehicle_category_id: cat.id, horizon: i + 1, target_week_start: isoDay(target), target_week_end: isoDay(addWeeks(target, 1)), forecasted_demand: wma.forecasts[i], required_vehicle_units: Math.ceil(wma.forecasts[i]) }); inputs.push(...wma.inputs[i].map((x: any) => ({ forecast_id: clientRecordId, source_type: x.sourceType, source_week_start: x.sourceWeek, source_value: x.sourceValue, input_order: x.inputOrder, weight: x.weight, weighted_contribution: x.weightedContribution }))); } } const rpc = await c.rpc("persist_forecast_run", { p_generated_by: p.userId, p_method: "WMA", p_idempotency_key: key, p_coverage_start: isoDay(manilaWeekStart(coverage)), p_records: records, p_inputs: inputs }); if (rpc.error) return denied(409, "Unable to persist forecast run atomically."); return Response.json({ ...rpc.data, insufficientPairs: [] }, { status: 201 }); } catch (e) { return denied(e instanceof Error && e.message === "forbidden" ? 403 : 500, e instanceof Error && e.message === "forbidden" ? "Forbidden." : "Unable to process forecast."); } }
