/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PaymentDetailsRouteImport } from './routes/payment-details'
import { Route as CustomerLandingRouteImport } from './routes/customer-landing'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CustomerProfileRouteImport } from './routes/customer_.profile'
import { Route as ApiVehiclesRouteImport } from './routes/api.vehicles'
import { Route as ApiVehicleFinderRouteImport } from './routes/api.vehicle-finder'
import { Route as ApiVehicleAnalyticsRouteImport } from './routes/api.vehicle-analytics'
import { Route as ApiSupplyEvaluationsRouteImport } from './routes/api.supply-evaluations'
import { Route as ApiRequirementsRouteImport } from './routes/api.requirements'
import { Route as ApiPaymentsRouteImport } from './routes/api.payments'
import { Route as ApiOperationalContextRouteImport } from './routes/api.operational-context'
import { Route as ApiNotificationsRouteImport } from './routes/api.notifications'
import { Route as ApiMasterDataRouteImport } from './routes/api.master-data'
import { Route as ApiMaintenanceRouteImport } from './routes/api.maintenance'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiForecastsRouteImport } from './routes/api.forecasts'
import { Route as ApiBookingsRouteImport } from './routes/api.bookings'
import { Route as ApiBookingMasterDataRouteImport } from './routes/api.booking-master-data'
import { Route as ApiAuditEventsRouteImport } from './routes/api.audit-events'
import { Route as ApiAllocationRecommendationsRouteImport } from './routes/api.allocation-recommendations'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminFleetRouteImport } from './routes/admin.fleet'
import { Route as AdminDecisionsRouteImport } from './routes/admin.decisions'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as ApiInternalRemindersRouteImport } from './routes/api.internal.reminders'
import { Route as ApiAuthSignUpRouteImport } from './routes/api.auth.sign-up'
import { Route as ApiAuthSignOutRouteImport } from './routes/api.auth.sign-out'
import { Route as ApiAuthSignInRouteImport } from './routes/api.auth.sign-in'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiAuthProfileRouteImport } from './routes/api.auth.profile'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentDetailsRoute = PaymentDetailsRouteImport.update({
  id: '/payment-details',
  path: '/payment-details',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLandingRoute = CustomerLandingRouteImport.update({
  id: '/customer-landing',
  path: '/customer-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer_/profile',
  path: '/customer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVehiclesRoute = ApiVehiclesRouteImport.update({
  id: '/api/vehicles',
  path: '/api/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVehicleFinderRoute = ApiVehicleFinderRouteImport.update({
  id: '/api/vehicle-finder',
  path: '/api/vehicle-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVehicleAnalyticsRoute = ApiVehicleAnalyticsRouteImport.update({
  id: '/api/vehicle-analytics',
  path: '/api/vehicle-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupplyEvaluationsRoute = ApiSupplyEvaluationsRouteImport.update({
  id: '/api/supply-evaluations',
  path: '/api/supply-evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequirementsRoute = ApiRequirementsRouteImport.update({
  id: '/api/requirements',
  path: '/api/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsRoute = ApiPaymentsRouteImport.update({
  id: '/api/payments',
  path: '/api/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperationalContextRoute = ApiOperationalContextRouteImport.update({
  id: '/api/operational-context',
  path: '/api/operational-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterDataRoute = ApiMasterDataRouteImport.update({
  id: '/api/master-data',
  path: '/api/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaintenanceRoute = ApiMaintenanceRouteImport.update({
  id: '/api/maintenance',
  path: '/api/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForecastsRoute = ApiForecastsRouteImport.update({
  id: '/api/forecasts',
  path: '/api/forecasts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingMasterDataRoute = ApiBookingMasterDataRouteImport.update({
  id: '/api/booking-master-data',
  path: '/api/booking-master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditEventsRoute = ApiAuditEventsRouteImport.update({
  id: '/api/audit-events',
  path: '/api/audit-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAllocationRecommendationsRoute =
  ApiAllocationRecommendationsRouteImport.update({
    id: '/api/allocation-recommendations',
    path: '/api/allocation-recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDecisionsRoute = AdminDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const ApiInternalRemindersRoute = ApiInternalRemindersRouteImport.update({
  id: '/api/internal/reminders',
  path: '/api/internal/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignUpRoute = ApiAuthSignUpRouteImport.update({
  id: '/api/auth/sign-up',
  path: '/api/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRoute
  '/customer-landing': typeof CustomerLandingRoute
  '/payment-details': typeof PaymentDetailsRoute
  '/sign-in': typeof SignInRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/decisions': typeof AdminDecisionsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/allocation-recommendations': typeof ApiAllocationRecommendationsRoute
  '/api/audit-events': typeof ApiAuditEventsRoute
  '/api/booking-master-data': typeof ApiBookingMasterDataRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/forecasts': typeof ApiForecastsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/maintenance': typeof ApiMaintenanceRoute
  '/api/master-data': typeof ApiMasterDataRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/operational-context': typeof ApiOperationalContextRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/requirements': typeof ApiRequirementsRoute
  '/api/supply-evaluations': typeof ApiSupplyEvaluationsRoute
  '/api/vehicle-analytics': typeof ApiVehicleAnalyticsRoute
  '/api/vehicle-finder': typeof ApiVehicleFinderRoute
  '/api/vehicles': typeof ApiVehiclesRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/internal/reminders': typeof ApiInternalRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRoute
  '/customer-landing': typeof CustomerLandingRoute
  '/payment-details': typeof PaymentDetailsRoute
  '/sign-in': typeof SignInRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/decisions': typeof AdminDecisionsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/allocation-recommendations': typeof ApiAllocationRecommendationsRoute
  '/api/audit-events': typeof ApiAuditEventsRoute
  '/api/booking-master-data': typeof ApiBookingMasterDataRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/forecasts': typeof ApiForecastsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/maintenance': typeof ApiMaintenanceRoute
  '/api/master-data': typeof ApiMasterDataRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/operational-context': typeof ApiOperationalContextRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/requirements': typeof ApiRequirementsRoute
  '/api/supply-evaluations': typeof ApiSupplyEvaluationsRoute
  '/api/vehicle-analytics': typeof ApiVehicleAnalyticsRoute
  '/api/vehicle-finder': typeof ApiVehicleFinderRoute
  '/api/vehicles': typeof ApiVehiclesRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/internal/reminders': typeof ApiInternalRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRoute
  '/customer-landing': typeof CustomerLandingRoute
  '/payment-details': typeof PaymentDetailsRoute
  '/sign-in': typeof SignInRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/decisions': typeof AdminDecisionsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/allocation-recommendations': typeof ApiAllocationRecommendationsRoute
  '/api/audit-events': typeof ApiAuditEventsRoute
  '/api/booking-master-data': typeof ApiBookingMasterDataRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/forecasts': typeof ApiForecastsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/maintenance': typeof ApiMaintenanceRoute
  '/api/master-data': typeof ApiMasterDataRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/operational-context': typeof ApiOperationalContextRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/requirements': typeof ApiRequirementsRoute
  '/api/supply-evaluations': typeof ApiSupplyEvaluationsRoute
  '/api/vehicle-analytics': typeof ApiVehicleAnalyticsRoute
  '/api/vehicle-finder': typeof ApiVehicleFinderRoute
  '/api/vehicles': typeof ApiVehiclesRoute
  '/customer_/profile': typeof CustomerProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/internal/reminders': typeof ApiInternalRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/customer'
    | '/customer-landing'
    | '/payment-details'
    | '/sign-in'
    | '/vehicles'
    | '/admin/activity'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/decisions'
    | '/admin/fleet'
    | '/admin/maintenance'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/api/allocation-recommendations'
    | '/api/audit-events'
    | '/api/booking-master-data'
    | '/api/bookings'
    | '/api/forecasts'
    | '/api/health'
    | '/api/maintenance'
    | '/api/master-data'
    | '/api/notifications'
    | '/api/operational-context'
    | '/api/payments'
    | '/api/requirements'
    | '/api/supply-evaluations'
    | '/api/vehicle-analytics'
    | '/api/vehicle-finder'
    | '/api/vehicles'
    | '/customer/profile'
    | '/admin/'
    | '/api/auth/profile'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up'
    | '/api/internal/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/contact'
    | '/customer'
    | '/customer-landing'
    | '/payment-details'
    | '/sign-in'
    | '/vehicles'
    | '/admin/activity'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/decisions'
    | '/admin/fleet'
    | '/admin/maintenance'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/api/allocation-recommendations'
    | '/api/audit-events'
    | '/api/booking-master-data'
    | '/api/bookings'
    | '/api/forecasts'
    | '/api/health'
    | '/api/maintenance'
    | '/api/master-data'
    | '/api/notifications'
    | '/api/operational-context'
    | '/api/payments'
    | '/api/requirements'
    | '/api/supply-evaluations'
    | '/api/vehicle-analytics'
    | '/api/vehicle-finder'
    | '/api/vehicles'
    | '/customer/profile'
    | '/admin'
    | '/api/auth/profile'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up'
    | '/api/internal/reminders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/customer'
    | '/customer-landing'
    | '/payment-details'
    | '/sign-in'
    | '/vehicles'
    | '/admin/activity'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/decisions'
    | '/admin/fleet'
    | '/admin/maintenance'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/api/allocation-recommendations'
    | '/api/audit-events'
    | '/api/booking-master-data'
    | '/api/bookings'
    | '/api/forecasts'
    | '/api/health'
    | '/api/maintenance'
    | '/api/master-data'
    | '/api/notifications'
    | '/api/operational-context'
    | '/api/payments'
    | '/api/requirements'
    | '/api/supply-evaluations'
    | '/api/vehicle-analytics'
    | '/api/vehicle-finder'
    | '/api/vehicles'
    | '/customer_/profile'
    | '/admin/'
    | '/api/auth/profile'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up'
    | '/api/internal/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  CustomerRoute: typeof CustomerRoute
  CustomerLandingRoute: typeof CustomerLandingRoute
  PaymentDetailsRoute: typeof PaymentDetailsRoute
  SignInRoute: typeof SignInRoute
  VehiclesRoute: typeof VehiclesRoute
  ApiAllocationRecommendationsRoute: typeof ApiAllocationRecommendationsRoute
  ApiAuditEventsRoute: typeof ApiAuditEventsRoute
  ApiBookingMasterDataRoute: typeof ApiBookingMasterDataRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  ApiForecastsRoute: typeof ApiForecastsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMaintenanceRoute: typeof ApiMaintenanceRoute
  ApiMasterDataRoute: typeof ApiMasterDataRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiOperationalContextRoute: typeof ApiOperationalContextRoute
  ApiPaymentsRoute: typeof ApiPaymentsRoute
  ApiRequirementsRoute: typeof ApiRequirementsRoute
  ApiSupplyEvaluationsRoute: typeof ApiSupplyEvaluationsRoute
  ApiVehicleAnalyticsRoute: typeof ApiVehicleAnalyticsRoute
  ApiVehicleFinderRoute: typeof ApiVehicleFinderRoute
  ApiVehiclesRoute: typeof ApiVehiclesRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  ApiAuthProfileRoute: typeof ApiAuthProfileRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiAuthSignUpRoute: typeof ApiAuthSignUpRoute
  ApiInternalRemindersRoute: typeof ApiInternalRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-details': {
      id: '/payment-details'
      path: '/payment-details'
      fullPath: '/payment-details'
      preLoaderRoute: typeof PaymentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-landing': {
      id: '/customer-landing'
      path: '/customer-landing'
      fullPath: '/customer-landing'
      preLoaderRoute: typeof CustomerLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer_/profile': {
      id: '/customer_/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vehicles': {
      id: '/api/vehicles'
      path: '/api/vehicles'
      fullPath: '/api/vehicles'
      preLoaderRoute: typeof ApiVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vehicle-finder': {
      id: '/api/vehicle-finder'
      path: '/api/vehicle-finder'
      fullPath: '/api/vehicle-finder'
      preLoaderRoute: typeof ApiVehicleFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vehicle-analytics': {
      id: '/api/vehicle-analytics'
      path: '/api/vehicle-analytics'
      fullPath: '/api/vehicle-analytics'
      preLoaderRoute: typeof ApiVehicleAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supply-evaluations': {
      id: '/api/supply-evaluations'
      path: '/api/supply-evaluations'
      fullPath: '/api/supply-evaluations'
      preLoaderRoute: typeof ApiSupplyEvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requirements': {
      id: '/api/requirements'
      path: '/api/requirements'
      fullPath: '/api/requirements'
      preLoaderRoute: typeof ApiRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments': {
      id: '/api/payments'
      path: '/api/payments'
      fullPath: '/api/payments'
      preLoaderRoute: typeof ApiPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operational-context': {
      id: '/api/operational-context'
      path: '/api/operational-context'
      fullPath: '/api/operational-context'
      preLoaderRoute: typeof ApiOperationalContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master-data': {
      id: '/api/master-data'
      path: '/api/master-data'
      fullPath: '/api/master-data'
      preLoaderRoute: typeof ApiMasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maintenance': {
      id: '/api/maintenance'
      path: '/api/maintenance'
      fullPath: '/api/maintenance'
      preLoaderRoute: typeof ApiMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forecasts': {
      id: '/api/forecasts'
      path: '/api/forecasts'
      fullPath: '/api/forecasts'
      preLoaderRoute: typeof ApiForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-master-data': {
      id: '/api/booking-master-data'
      path: '/api/booking-master-data'
      fullPath: '/api/booking-master-data'
      preLoaderRoute: typeof ApiBookingMasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-events': {
      id: '/api/audit-events'
      path: '/api/audit-events'
      fullPath: '/api/audit-events'
      preLoaderRoute: typeof ApiAuditEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/allocation-recommendations': {
      id: '/api/allocation-recommendations'
      path: '/api/allocation-recommendations'
      fullPath: '/api/allocation-recommendations'
      preLoaderRoute: typeof ApiAllocationRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/decisions': {
      id: '/admin/decisions'
      path: '/decisions'
      fullPath: '/admin/decisions'
      preLoaderRoute: typeof AdminDecisionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/internal/reminders': {
      id: '/api/internal/reminders'
      path: '/api/internal/reminders'
      fullPath: '/api/internal/reminders'
      preLoaderRoute: typeof ApiInternalRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-up': {
      id: '/api/auth/sign-up'
      path: '/api/auth/sign-up'
      fullPath: '/api/auth/sign-up'
      preLoaderRoute: typeof ApiAuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDecisionsRoute: typeof AdminDecisionsRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDecisionsRoute: AdminDecisionsRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  CustomerRoute: CustomerRoute,
  CustomerLandingRoute: CustomerLandingRoute,
  PaymentDetailsRoute: PaymentDetailsRoute,
  SignInRoute: SignInRoute,
  VehiclesRoute: VehiclesRoute,
  ApiAllocationRecommendationsRoute: ApiAllocationRecommendationsRoute,
  ApiAuditEventsRoute: ApiAuditEventsRoute,
  ApiBookingMasterDataRoute: ApiBookingMasterDataRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  ApiForecastsRoute: ApiForecastsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMaintenanceRoute: ApiMaintenanceRoute,
  ApiMasterDataRoute: ApiMasterDataRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiOperationalContextRoute: ApiOperationalContextRoute,
  ApiPaymentsRoute: ApiPaymentsRoute,
  ApiRequirementsRoute: ApiRequirementsRoute,
  ApiSupplyEvaluationsRoute: ApiSupplyEvaluationsRoute,
  ApiVehicleAnalyticsRoute: ApiVehicleAnalyticsRoute,
  ApiVehicleFinderRoute: ApiVehicleFinderRoute,
  ApiVehiclesRoute: ApiVehiclesRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  ApiAuthProfileRoute: ApiAuthProfileRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiAuthSignUpRoute: ApiAuthSignUpRoute,
  ApiInternalRemindersRoute: ApiInternalRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
